language: node_js

node_js:
  - 10

dist: trusty

jobs:
  include:
    - stage: test
      script:
        - npm run test:coverage
        - npm run coverage:collect
    - stage: build
      script:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        commiter_from_gh: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
        target_branch: gh-pages
        local_dir: build

addons:
  sonarcloud:
    organization: "luizzzdev"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
